// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-U0KOJJCTck64H0tf6TJVo2PWhRiLtEA',
    appId: '1:664074127987:web:713ce5ff707f7736a67806',
    messagingSenderId: '664074127987',
    projectId: 'totalizasubs',
    authDomain: 'totalizasubs.firebaseapp.com',
    storageBucket: 'totalizasubs.firebasestorage.app',
    measurementId: 'G-T7LG4ERF42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXX45o9hwuINmHis8ygQAHX8ubRWwRh8',
    appId: '1:664074127987:android:a30d4b777ae8bf5aa67806',
    messagingSenderId: '664074127987',
    projectId: 'totalizasubs',
    storageBucket: 'totalizasubs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRiVB19woHJ9ekeqr3JERzDWVgd2ZuJ0',
    appId: '1:664074127987:ios:498e19616e04cb4fa67806',
    messagingSenderId: '664074127987',
    projectId: 'totalizasubs',
    storageBucket: 'totalizasubs.firebasestorage.app',
    iosBundleId: 'com.example.totalizaSubs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRiVB19woHJ9ekeqr3JERzDWVgd2ZuJ0',
    appId: '1:664074127987:ios:498e19616e04cb4fa67806',
    messagingSenderId: '664074127987',
    projectId: 'totalizasubs',
    storageBucket: 'totalizasubs.firebasestorage.app',
    iosBundleId: 'com.example.totalizaSubs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-U0KOJJCTck64H0tf6TJVo2PWhRiLtEA',
    appId: '1:664074127987:web:0da9185ed2616913a67806',
    messagingSenderId: '664074127987',
    projectId: 'totalizasubs',
    authDomain: 'totalizasubs.firebaseapp.com',
    storageBucket: 'totalizasubs.firebasestorage.app',
    measurementId: 'G-109SEVTWLH',
  );
}
